# sonar-project.properties
# SIT223/753 Task 7.1C - Part 2 Task 1: SonarCloud.io integration
# Aaryan Dandona (s224842524)

sonar.projectKey=automacioai-code_8.2CDevSecOps
sonar.organization=automacioai-code

sonar.host.url=https://sonarcloud.io

sonar.sources=.
sonar.exclusions=node_modules/**,test/**,tests/**,public/js/bundle.js,.sonar-scanner/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.projectName=NodeJS Goof Vulnerable App
sonar.sourceEncoding=UTF-8
